export const TOGGLE_SIDEBAR = " TOGGLE_SIDEBAR";
export const CLEAR_TEXT = "CLEAR_TEXT";
export const EMPTY_ERR = "EMPTY_ERR";
export const REVERSE_LOADING  = "REVERSE_LOADING";
export const SET_LOADER  = "SET_LOADER";
export const  ADD_CARGO_DETAILS_SUCCESS  = " ADD_CARGO_DETAILS_SUCCESS";
export const  ADD_CARGO_DETAILS_ERROR = " ADD_CARGO_DETAILS_ERROR";



